### ISSUE TITLE
Re-think e2e support for voyager

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-voyager-bot#108]
https://github.com/vector-im/riot-web/issues/2277 gives a pretty big hint that voyager shouldn't be autojoining e2e rooms

**Comment by jcgruenhage** [comment]
That doesn't rule out e2e though, since IMHO when it is explicitly invited, the drawback of some server knowing the conversation is obviously not concerning the people inviting the bot anyway.

**Comment by jcgruenhage** [comment]
I agree though, that the bot should instantly delete any non-current session keys, and delete everything it doesn't need to know for it's operation.

**Comment by turt2live** [comment]
Joining upon invite is an explicit action, and would probably be considered safe to join. However the bot's current behaviour is to join any room it sees a link to, such as #megolm:matrix.org.

Voyager is useless in encrypted rooms because #20 isn't implemented. It's unlikely that voyager will encounter public encrypted rooms, and people still have the option to kick/ban/invite the bot at will to their room. 

I don't think voyager can detect if the room is encrypted or not without joining, so it would need to join, check, and leave immediately if it finds that it's encrypted and doesn't pass some entry condition.

Might even be worthwhile to go as far as only allowing the bot to decrypt when authorized by a room mod/admin (or whoever has permission to configure the room). The exchange would look something like this:

```
voyager joined the room
<voyager (unencrypted)> This room is encrypted. Please open a 1:1 conversation with me and send the message `!voyager enableroom #megolm:matrix.org` if you want me to decrypt messages to find more rooms. Please kick/ban me otherwise.
```

Although if the bot isn't invited, it should probably still leave without comment. Random bots appearing in rooms is scary, but random bots that don't reply in a sensitive room are scarier, if only just.

This might be a problem with https://github.com/matrix-org/matrix-doc/issues/884 though (because voyager wouldn't be able to send a plaintext message)

**Comment by turt2live** [comment]
Closing in favour of https://github.com/turt2live/matrix-voyager-bot/issues/210 which describes the plan of action. TLDR: Voyager will leave encrypted rooms.
