### ISSUE TITLE
"Log in with matrix" to help with joining rooms and to illustrate your own involvement in the network?

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-voyager-bot#163]
Related: https://github.com/turt2live/matrix-voyager-bot/issues/19

It might be interesting for people to see visually which clusters they are participating in and by proxy which rooms they might be interested in. This would need a "Log in with [matrix]" button somewhere on the page that would act as a very minimalist client. Clicking on nodes would give you the option to join the room instead of just getting a link to it. Keep client interactions completely client-side. The backend should be completely unaware of the user's credentials, login, etc.

Feedback from people who use the bot/graph would be appreciated, as this idea came to mind as a way to counter the "how do I join a room?" question.

**Comment by ara4n** [comment]
this would be cool, although just hyperlinking matrix.to is even easier ;)

**Comment by turt2live** [comment]
Closing in favour of https://github.com/turt2live/matrix-voyager-bot/issues/19 (Matthew's suggestion).
